name: Build Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yml"

  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: "finance-dashboard/backend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::593108103435:role/GH-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
